# Generated by Django 3.2.5 on 2021-08-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_dt', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('weather_main', models.CharField(max_length=15)),
                ('weather_desc', models.CharField(max_length=40)),
                ('rain_bool', models.SmallIntegerField()),
                ('icon', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('future_dt', models.DateField()),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('weather_main', models.CharField(max_length=15)),
                ('weather_desc', models.CharField(max_length=40)),
                ('rain_bool', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField()),
                ('future_dt', models.DateTimeField()),
                ('temp', models.FloatField()),
                ('feels_like', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('wind_deg', models.IntegerField()),
                ('clouds', models.IntegerField()),
                ('weather_main', models.CharField(max_length=15)),
                ('weather_desc', models.CharField(max_length=40)),
                ('rain_bool', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Times',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=15)),
                ('trip_id', models.CharField(max_length=40)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('shape_dist', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=15)),
                ('trip_id', models.CharField(max_length=40)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('shape_dist', models.FloatField()),
            ],
        ),
    ]
